### ISSUE TITLE
Timepicker arrow icons are missing

### ISSUE THREAD

**Issue by guiramadasa** [puikinsh/Bootstrap-Admin-Template#53]
I noted icons of up and down arrow keys of links/buttons in timepicker widget are not appearing properly. They are functioning properly as intended, but icons seems to be misplaced, transparent arrow seems appearing above

. I checked in chrome.

Please see the screenshot attached.

**Comment by CERPSoftwareSolutions** [comment]
The same problem occurred with me.

![image](https://github.com/puikinsh/Bootstrap-Admin-Template/assets/107601660/7fdff42a-6a11-470b-99ce-ac79a00f792e)
