### ISSUE TITLE
Build failing at npm run build

### ISSUE THREAD

**Issue by OldProgramCoder** [puikinsh/Bootstrap-Admin-Template#71]
My build is failing when I run the step   > npm run build

out put is 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild bootstrap-admin-template@2.4.0
6 info build bootstrap-admin-template@2.4.0
7 verbose unsafe-perm in lifecycle true
8 info bootstrap-admin-template@2.4.0 Failed to exec build script
9 verbose stack Error: bootstrap-admin-template@2.4.0 build: `npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid bootstrap-admin-template@2.4.0
11 verbose cwd c:\Temp\metis7
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error bootstrap-admin-template@2.4.0 build: `npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js`
17 error Exit status 1
18 error Failed at the bootstrap-admin-template@2.4.0 build script 'npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js'.
18 error This is most likely a problem with the bootstrap-admin-template package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs bootstrap-admin-template
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls bootstrap-admin-template
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

any help would be appreciated.

thanks 
Colin

**Comment by onokumus** [comment]
@OldProgramCoder 
What is the result of the following commands, respectively?

```sh
npm run clean
./node_modules/.bin/gulp
./node_modules/.bin/assemble --file assemblefile.js
```

**Comment by OldProgramCoder** [comment]
Not 100% sure of how you want these run but ....    If I have done it wrong let me know. 

Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)
$ npm run clean
\> bootstrap-admin-template@2.4.0 clean C:\temp\metis3
\> rimraf public dist

Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)
$ npm run clean   ./node_modules/.bin/gulp
\> bootstrap-admin-template@2.4.0 clean C:\temp\metis3
\> rimraf public dist "./node_modules/.bin/gulp"


Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)
$ npm run clean  ./node_modules/.bin/assemble --file assemblefile.js
\> bootstrap-admin-template@2.4.0 clean C:\temp\metis3
\> rimraf public dist "./node_modules/.bin/assemble" "assemblefile.js"
 
**Further information**
**I stalled npm v6.6 today and here are the messages I get throughout the process**

Colin@COLINS-M6800 MINGW64 /c/temp
$ npm install
npm ERR! registry error parsing json
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

\> bootstrap-admin-template@2.4.0 preinstall C:\temp\metis3
\> bower install              **<< this started automatically which was a change from npm 4.5**

**\< everything runs well for a while with good out put...   and then>** 

bower rangy-1.3#master                      invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["uncompressed/rangy-core.js","uncompressed/rangy-cssclassapplier.js","uncompressed/rangy-highlighter.js","uncompressed/rangy-selectionsaverestore.js","uncompressed/rangy-serializer.js","uncompressed/rangy-textrange.js"]
bower rangy-1.3#master                          resolved https://github.com/noap/rangy-1.3.git#d2b26285b8

**\< everything runs well  and the directory seems to be out put and then command returns with >** 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)

here I run  > npm run build

Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)
$ npm run build
\> bootstrap-admin-template@2.4.0 build C:\temp\metis3
\> npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js
\> bootstrap-admin-template@2.4.0 clean C:\temp\metis3
\> rimraf public dist
'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-admin-template@2.4.0 build: `npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-admin-template@2.4.0 build script 'npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-admin-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && ./node_modules/.bin/gulp && ./node_modules/.bin/assemble --file assemblefile.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-admin-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-admin-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\metis3\npm-debug.log

Colin@COLINS-M6800 MINGW64 /c/temp/metis3 (master)
$

**Comment by onokumus** [comment]
@OldProgramCoder

Check it out now.

https://github.com/puikinsh/Bootstrap-Admin-Template/blob/master/package.json#L33-L36

**Comment by OldProgramCoder** [comment]
Works good. Much appreciated.   The only thing that needs to done is fix issue 67 which affects the bower.json  file.   Then this would build right out of the box.

Nice site by the way.   I really like it.

https://github.com/puikinsh/Bootstrap-Admin-Template/issues/67   << bower.json
