### ISSUE TITLE
Style Switch is in scroll bar

### ISSUE THREAD

**Issue by OldProgramCoder** [puikinsh/Bootstrap-Admin-Template#72]
The entire display, headers and nav bar was extending right too far and was partially  hidden by the right scrollbar.   I fixed this by putting it in a container.   

Unfortunately the gear icon for the style switcher is still partly hidden by the scroll bar and when you pop it out the blue pick box is partially in the scroll bar.  Eventually it seems to rise to the top and cover the scroll bar.   

Question,  how to move the switcher a little to the left so it is with main window and on in the scroll bar.

Thanks,

**Comment by OldProgramCoder** [comment]
I going to correct myself and say that the fix I thought I had is only working on the body.  Not working on the nav bar.
![metis picture](https://cloud.githubusercontent.com/assets/22086465/18799464/afdea6f2-81a5-11e6-8eb9-322d7798dd91.png)

**Comment by onokumus** [comment]
@OldProgramCoder 
I don't see any problem in localhost. And yes, there is a problem https://colorlib.com/polygon/metis/
style-switcher menu doesn't open in internet explorer and edge on windows.

**Comment by OldProgramCoder** [comment]
Check and it works fine on > gulp server
problem exists running in debug   out of visual studio on  EI 11, Firefox and Chrome.

The visual problem that you see on https://colorlib.com/polygon/metis/# running in EI,  I see in every browser.   However on my build, the Style Switch does work on EI.

**Comment by OldProgramCoder** [comment]
Looking around I found this 
http://stackoverflow.com/questions/17045132/scrollbar-overlay-in-ie10-how-do-you-stop-that

I created a bootstrap-custom.css file and put the following in the file.

body {
    -ms-overflow-style: scrollbar;
}

I loaded this file after bootstrap.css and it fixed the problem.
